# Generated by Django 6.0 on 2025-12-27 09:11

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='datum')),
                ('average_mood', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='genomsnittligt humör')),
                ('min_mood', models.PositiveSmallIntegerField(verbose_name='lägsta humör')),
                ('max_mood', models.PositiveSmallIntegerField(verbose_name='högsta humör')),
                ('entry_count', models.PositiveSmallIntegerField(verbose_name='antal noteringar')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='uppdaterad')),
            ],
            options={
                'verbose_name': 'dagssammanfattning',
                'verbose_name_plural': 'dagssammanfattningar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_level', models.PositiveSmallIntegerField(help_text='1 = Väldigt låg, 10 = Väldigt bra', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='humörnivå')),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='anteckning')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='tidpunkt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='skapad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='uppdaterad')),
            ],
            options={
                'verbose_name': 'humörnotering',
                'verbose_name_plural': 'humörnoteringar',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='namn')),
                ('color', models.CharField(default='#6B7280', help_text='Hex-färgkod, t.ex. #FF6D2A', max_length=7, verbose_name='färg')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='skapad')),
            ],
            options={
                'verbose_name': 'tagg',
                'verbose_name_plural': 'taggar',
                'ordering': ['name'],
            },
        ),
    ]
