# Generated by Django 6.0 on 2025-12-27 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaggregate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_aggregates', to=settings.AUTH_USER_MODEL, verbose_name='användare'),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL, verbose_name='användare'),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='användare'),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='moods.tag', verbose_name='taggar'),
        ),
        migrations.AddIndex(
            model_name='dailyaggregate',
            index=models.Index(fields=['user', '-date'], name='moods_daily_user_id_650bc9_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyaggregate',
            index=models.Index(fields=['user', 'date'], name='moods_daily_user_id_9a2ed3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyaggregate',
            unique_together={('user', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', '-timestamp'], name='moods_moode_user_id_51b8aa_idx'),
        ),
        migrations.AddIndex(
            model_name='moodentry',
            index=models.Index(fields=['user', 'timestamp'], name='moods_moode_user_id_40ebef_idx'),
        ),
    ]
