# Generated by Django 6.0 on 2025-12-28 02:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='datum')),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='sömntimmar')),
                ('sleep_quality', models.PositiveSmallIntegerField(blank=True, help_text='1 = Mycket dålig, 5 = Mycket bra', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='sömnkvalitet')),
                ('energy', models.PositiveSmallIntegerField(blank=True, help_text='1 = Mycket låg, 5 = Mycket hög', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='energi')),
                ('appetite', models.PositiveSmallIntegerField(blank=True, help_text='1 = Ingen aptit, 5 = Mycket god aptit', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='aptit')),
                ('anxiety', models.PositiveSmallIntegerField(blank=True, help_text='1 = Ingen ångest, 5 = Mycket stark ångest', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='ångest')),
                ('stress', models.PositiveSmallIntegerField(blank=True, help_text='1 = Ingen stress, 5 = Mycket hög stress', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='stress')),
                ('concentration', models.PositiveSmallIntegerField(blank=True, help_text='1 = Mycket dålig, 5 = Mycket bra', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='koncentration')),
                ('exercise', models.CharField(choices=[('none', 'Ingen'), ('light', 'Lätt'), ('moderate', 'Måttlig'), ('intense', 'Intensiv')], default='none', max_length=10, verbose_name='träning')),
                ('social', models.CharField(choices=[('none', 'Ingen'), ('little', 'Lite'), ('some', 'En del'), ('lots', 'Mycket')], default='none', max_length=10, verbose_name='socialt')),
                ('alcohol', models.CharField(choices=[('none', 'Ingen'), ('light', 'Lite'), ('moderate', 'Måttligt'), ('heavy', 'Mycket')], default='none', max_length=10, verbose_name='alkohol')),
                ('other_substances', models.CharField(choices=[('none', 'Ingen'), ('light', 'Lite'), ('moderate', 'Måttligt'), ('heavy', 'Mycket')], default='none', max_length=10, verbose_name='andra substanser')),
                ('notes', models.TextField(blank=True, max_length=1000, verbose_name='anteckningar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='skapad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='uppdaterad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL, verbose_name='användare')),
            ],
            options={
                'verbose_name': 'daganteckning',
                'verbose_name_plural': 'daganteckningar',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='moods_daily_user_id_3de6ac_idx'), models.Index(fields=['user', 'date'], name='moods_daily_user_id_f96066_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
