# Generated by Django 6.0 on 2025-12-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_add_daily_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='alcohol',
            field=models.CharField(choices=[('none', 'Inga'), ('light', 'Lite'), ('moderate', 'Måttligt'), ('heavy', 'Mycket')], default='none', max_length=10, verbose_name='alkohol'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='other_substances',
            field=models.CharField(choices=[('none', 'Inga'), ('light', 'Lite'), ('moderate', 'Måttligt'), ('heavy', 'Mycket')], default='none', max_length=10, verbose_name='andra substanser'),
        ),
    ]
