# Generated by Django 6.0 on 2025-12-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0004_alter_dailylog_alcohol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='daylight',
            field=models.CharField(choices=[('none', 'Inget'), ('little', 'Lite'), ('some', 'En del'), ('lots', 'Mycket')], default='none', max_length=10, verbose_name='dagsljus'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='nicotine',
            field=models.CharField(choices=[('none', 'Inga'), ('light', 'Lite'), ('moderate', 'Måttligt'), ('heavy', 'Mycket')], default='none', max_length=10, verbose_name='nikotin'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='exercise',
            field=models.CharField(choices=[('none', 'Ingen'), ('light', 'Lätt'), ('moderate', 'Måttlig'), ('intense', 'Intensiv')], default='none', max_length=10, verbose_name='fysisk aktivitet'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='other_substances',
            field=models.CharField(choices=[('none', 'Inga'), ('light', 'Lite'), ('moderate', 'Måttligt'), ('heavy', 'Mycket')], default='none', max_length=10, verbose_name='droger'),
        ),
    ]
