# Generated by Django 6.0 on 2025-12-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0005_add_nicotine_and_daylight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('none', 'Inga'), ('light', 'Lite'), ('moderate', 'Måttligt'), ('heavy', 'Mycket')], max_length=10, null=True, verbose_name='alkohol'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='daylight',
            field=models.CharField(blank=True, choices=[('none', 'Inget'), ('little', 'Lite'), ('some', 'En del'), ('lots', 'Mycket')], max_length=10, null=True, verbose_name='dagsljus'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='exercise',
            field=models.CharField(blank=True, choices=[('none', 'Ingen'), ('light', 'Lätt'), ('moderate', 'Måttlig'), ('intense', 'Intensiv')], max_length=10, null=True, verbose_name='fysisk aktivitet'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='nicotine',
            field=models.CharField(blank=True, choices=[('none', 'Inga'), ('light', 'Lite'), ('moderate', 'Måttligt'), ('heavy', 'Mycket')], max_length=10, null=True, verbose_name='nikotin'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='other_substances',
            field=models.CharField(blank=True, choices=[('none', 'Inga'), ('light', 'Lite'), ('moderate', 'Måttligt'), ('heavy', 'Mycket')], max_length=10, null=True, verbose_name='droger'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='social',
            field=models.CharField(blank=True, choices=[('none', 'Ingen'), ('little', 'Lite'), ('some', 'En del'), ('lots', 'Mycket')], max_length=10, null=True, verbose_name='socialt'),
        ),
    ]
