# Generated by Django 6.0 on 2025-12-28 03:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0006_make_choice_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='loggad'),
        ),
    ]
