# Generated by Django 6.0 on 2025-12-28 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0007_add_dailylog_logged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyaggregate',
            name='logged_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='loggad'),
        ),
    ]
