# Generated by Django 6.0 on 2025-12-27 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'En användare med denna e-postadress finns redan.'}, max_length=254, unique=True, verbose_name='e-postadress')),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='visningsnamn')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('is_staff', models.BooleanField(default=False, verbose_name='personal')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registreringsdatum')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'användare',
                'verbose_name_plural': 'användare',
            },
        ),
    ]
