/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkapaKontoRouteImport } from './routes/skapa-konto'
import { Route as LoggaInRouteImport } from './routes/logga-in'
import { Route as HistorikRouteImport } from './routes/historik'
import { Route as GlomtLosenordRouteImport } from './routes/glomt-losenord'
import { Route as AterstallLosenordRouteImport } from './routes/aterstall-losenord'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const SkapaKontoRoute = SkapaKontoRouteImport.update({
  id: '/skapa-konto',
  path: '/skapa-konto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorikRoute = HistorikRouteImport.update({
  id: '/historik',
  path: '/historik',
  getParentRoute: () => rootRouteImport,
} as any)
const GlomtLosenordRoute = GlomtLosenordRouteImport.update({
  id: '/glomt-losenord',
  path: '/glomt-losenord',
  getParentRoute: () => rootRouteImport,
} as any)
const AterstallLosenordRoute = AterstallLosenordRouteImport.update({
  id: '/aterstall-losenord',
  path: '/aterstall-losenord',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/glomt-losenord': typeof GlomtLosenordRoute
  '/historik': typeof HistorikRoute
  '/logga-in': typeof LoggaInRoute
  '/skapa-konto': typeof SkapaKontoRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/glomt-losenord': typeof GlomtLosenordRoute
  '/historik': typeof HistorikRoute
  '/logga-in': typeof LoggaInRoute
  '/skapa-konto': typeof SkapaKontoRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aterstall-losenord': typeof AterstallLosenordRoute
  '/glomt-losenord': typeof GlomtLosenordRoute
  '/historik': typeof HistorikRoute
  '/logga-in': typeof LoggaInRoute
  '/skapa-konto': typeof SkapaKontoRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aterstall-losenord'
    | '/glomt-losenord'
    | '/historik'
    | '/logga-in'
    | '/skapa-konto'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aterstall-losenord'
    | '/glomt-losenord'
    | '/historik'
    | '/logga-in'
    | '/skapa-konto'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/aterstall-losenord'
    | '/glomt-losenord'
    | '/historik'
    | '/logga-in'
    | '/skapa-konto'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AterstallLosenordRoute: typeof AterstallLosenordRoute
  GlomtLosenordRoute: typeof GlomtLosenordRoute
  HistorikRoute: typeof HistorikRoute
  LoggaInRoute: typeof LoggaInRoute
  SkapaKontoRoute: typeof SkapaKontoRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skapa-konto': {
      id: '/skapa-konto'
      path: '/skapa-konto'
      fullPath: '/skapa-konto'
      preLoaderRoute: typeof SkapaKontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historik': {
      id: '/historik'
      path: '/historik'
      fullPath: '/historik'
      preLoaderRoute: typeof HistorikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glomt-losenord': {
      id: '/glomt-losenord'
      path: '/glomt-losenord'
      fullPath: '/glomt-losenord'
      preLoaderRoute: typeof GlomtLosenordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aterstall-losenord': {
      id: '/aterstall-losenord'
      path: '/aterstall-losenord'
      fullPath: '/aterstall-losenord'
      preLoaderRoute: typeof AterstallLosenordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AterstallLosenordRoute: AterstallLosenordRoute,
  GlomtLosenordRoute: GlomtLosenordRoute,
  HistorikRoute: HistorikRoute,
  LoggaInRoute: LoggaInRoute,
  SkapaKontoRoute: SkapaKontoRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
